### ISSUE TITLE
一件有点悲伤的事情

### ISSUE THREAD

**Issue by imsobear** [imsobear/tec_blog#58]
![](https://img.alicdn.com/tfs/TB1sIgXQpXXXXawXXXXXXXXXXXX-3264-2448.jpg)

事情是这样的
某天下班回家，照例打开扫地机器人
接着就回到卧室，玩着手机听着机器人的嗡嗡声
突然
某人突然说「毛豆是不是拉屎了」
在一股狗屎味中我冲出了卧室
我的天
毛豆拉屎了
毛豆不仅拉屎了
而且机器人扫。。。扫了。。。毛豆的。。。屎
内心已然崩溃的我随即拿起浴室的喷头对机器人一顿猛喷
于是，如你所愿
进屎加进水的机器人无法工作了

![](https://img.alicdn.com/tfs/TB1bZrFQpXXXXXdXVXXXXXXXXXX-3264-2448.jpg)

于是，在某个慵懒的午后
有人拿着螺丝刀拆
有人拿着吹风机吹
还有只🐶趴在那里发呆
还是得承认 iRobot 的机器人模块化设计的很棒
还有电路板焊的也很工整漂亮
然而最终还是未能复活过来
留着拖地机器人一个人独自过活
唉
一个悲伤的故事

> 附图：iRobot 漂亮工整的电路板

**Comment by wakefun** [comment]
狗：“抢我的屎？！”
